---
- name: Converge
  hosts: all
  roles:
    - role: ../../..
      vars:
        ludus_ar_splunk_url: https://download.splunk.com/products/splunk/releases/9.4.7/linux/splunk-9.4.7-2a9293b80994-linux-amd64.deb
        ludus_ar_splunk_password: changeme123!
  ignore_errors: yes
