---
- name: Converge
  hosts: all
  roles:
    - role: ../../..
      vars:
        ludus_ar_splunk_url: https://download.splunk.com/products/splunk/releases/10.0.2/linux/splunk-10.0.2-e2d18b4767e9-linux-amd64.tgz
        ludus_ar_splunk_password: changeme123!
  ignore_errors: yes
